name: CI/CD for Node.js with Docker and AWS Lightsail

on:
  push: # main이나 develop 브랜치에 push가 되었을 때 실행
    branches: 
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up known hosts
        run: |
          echo "$${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 3. Docker 이미지 빌드 및 Lightsail 서버로 전송
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=$(date +'%Y%m%d%H%M%S')
          docker build -t my-app:$IMAGE_TAG .
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_PUBLIC_IP }} \
            "docker load < $(docker save my-app:$IMAGE_TAG)"

      # 4. Lightsail 서버에서 Docker Compose 배포
      - name: Deploy on Lightsail
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_PUBLIC_IP }} << EOF
            cd /path/to/your/app
            echo "Updating Docker Compose service..."
            docker-compose down
            docker-compose up -d
          EOF  